name: project_3_1
description: Money Manager App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
 

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/money_manager-removebg-preview.png"

